{title: 'Simple Genius : Sean King and Michelle Maxwell Series #3',
 genre: 'Suspens',
 discription: 'In a world of secrets, human genius is power. And sometimes it is simply deadly . . .Near Washington, D.C., there are two clandestine institutions: the worlds most unusual laboratory and a secret CIA training camp. Drawn to these sites by a murder, ex-Secret Service agent Sean King encounters a dark world of mathematicians, codes, and spies. His search for answers soon leads him to more shocking violence-and an autistic girl with an extraordinary genius.Now, only by working with his embattled partner, Michelle Maxwell, can he catch a killer...and solve a stunning mystery that threatens the entire nation.',
 author: 'David Baldacci',
 publisher: 'Grand Central Publishing',
 pages: '448',
 image_url: 'https://prodimage.images-bn.com/pimages/9781455550807_p0_v2_s550x406.jpg',
 buy_url: 'https://www.barnesandnoble.com/w/simple-genius-david-baldacci/1100298487?ean=9781455550807#/'
},
{title: 'Absolute Power',
 genre: 'Suspens',
 discription: 'In a heavily guarded mansion in a posh Virginia suburb, a man and a woman start to make love, trapping Luther Whitney, a career break-in artist, behind a secret wall. Then the passion turns deadly, and Luther is running into the night. Because what he has just seen is a brutal murder involving Alan Richmond, the president of the United States, the man with...Absolute Power.',
 author: 'David Baldacci',
 publisher: 'Grand Central Publishing',
 pages: '704',
 image_url: 'https://prodimage.images-bn.com/pimages/9780446566568_p0_v1_s550x406.jpg',
 buy_url: 'https://www.barnesandnoble.com/w/absolute-power-david-baldacci/1100307672#/'
},
{title: 'The Simple Truth',
 genre: 'Suspens',
 discription: 'With his New York Times bestsellers Absolute Power, Total Control, and The Winner, David Baldacci proved beyond a doubt that he can break new ground every time out of the box. Now he does it again with his most powerful work yet, a heart-pounding thriller that brings to life two vastly different worlds joined by a deadly secret, and by a man and woman searching for...',
 author: 'David Baldacci',
 publisher: 'Grand Central Publishing',
 pages: '544',
 image_url: 'https://prodimage.images-bn.com/pimages/9780446607711_p0_v2_s550x406.jpg',
 buy_url: 'https://www.barnesandnoble.com/w/simple-truth-david-baldacci/1100305747?ean=9780446607711#/'
},
